---
- name: TShock - download tshock release 4.5.5
  get_url:
    url: https://github.com/Pryaxis/TShock/releases/download/v4.5.5/TShock4.5.5_Terraria_1.4.2.3.zip
    dest: /tmp/tshock.4.5.5.zip
    mode: '0644'

- name: TShock - Create temp path
  file:
    path: /tmp/tshock/
    state: directory

- name: TShock - Extract release
  unarchive:
    src: /tmp/tshock.4.5.5.zip
    dest: /tmp/tshock/
    creates: no
    remote_src: True

- name: TShock - Create server directory
  file:
    path: /home/terraria/tshock/
    owner: terraria
    group: terraria
    state: directory
    mode: '0755'

- name: TShock - Copy server files in place
  copy:
    src: /tmp/tshock/
    dest: /home/terraria/tshock/
    owner: terraria
    group: terraria
    remote_src: True

- name: TShock - Create world directory
  file:
    path: /home/terraria/tshock/world/
    owner: terraria
    group: terraria
    state: directory
    mode: '0755'

- name: TShock - Copy world_check.sh script in place
  copy:
    src: home/terraria/tshock/world_check.sh
    dest: /home/terraria/tshock/world_check.sh
    owner: terraria
    group: terraria
    mode: '0755'

- name: TShock - Copy tshock service file in place
  copy:
    src: etc/systemd/system/tshock.service
    dest: /etc/systemd/system/tshock.service

- name: TShock - Enable and start tshock service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: tshock
